"""реоганизация пакетов

Revision ID: 2c25e0d857a7
Revises: ca9cf5f69f6a
Create Date: 2023-04-02 13:03:17.379275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c25e0d857a7'
down_revision = 'ca9cf5f69f6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
